### ISSUE TITLE
Criar QRCode

### ISSUE THREAD

**Issue by rodrigowaters** [rodrigowaters/fisl-16#2]
- [x] AGENDA
- [x] SUMO
- [x] L10N
- [x] FIREFOX OS
- [x] DEV TOOLS
- [x] WOMOZ
- [x] WEBMAKER
- [x] FSA
- [x] LISTA

**Comment by SamuelMoraesF** [comment]
Faça o QR Code abrir o link no `mzl.la`, no caso de treta podemos alterar a URL de destino sem precisar recriar o QR. Algo como:

QR > http://mzl.la/fisl15-womoz > https://destino.com/pagina
